stages:
  - test

cache:
  paths:
    - src/GR.WebHosts/GR.Cms/wwwroot/lib/
test_projects:
  stage: test
  only:
    - develop
  script:
    - dotnet build ./GR.sln
    - dotnet test ./src/GR.Tests/GR.Core.Tests/GR.Core.Tests.csproj